name: "pg_to_firebolt"
version: "1.0.0"
config-version: 2

profile: "pg_to_firebolt"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  pg_to_firebolt:
    staging:
      +materialized: view
    marts:
      +materialized: table
